# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.get_user_jira_integrations_response import GetUserJiraIntegrationsResponse

class TestGetUserJiraIntegrationsResponse(unittest.TestCase):
    """GetUserJiraIntegrationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUserJiraIntegrationsResponse:
        """Test GetUserJiraIntegrationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUserJiraIntegrationsResponse`
        """
        model = GetUserJiraIntegrationsResponse()
        if include_optional:
            return GetUserJiraIntegrationsResponse(
                integrations = [
                    odin_sdk.models.jira_integration.JiraIntegration(
                        uid = '', 
                        jira_email = '', )
                    ]
            )
        else:
            return GetUserJiraIntegrationsResponse(
                integrations = [
                    odin_sdk.models.jira_integration.JiraIntegration(
                        uid = '', 
                        jira_email = '', )
                    ],
        )
        """

    def testGetUserJiraIntegrationsResponse(self):
        """Test GetUserJiraIntegrationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
