# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.save_on_prem_confluence_connector_info_response import SaveOnPremConfluenceConnectorInfoResponse

class TestSaveOnPremConfluenceConnectorInfoResponse(unittest.TestCase):
    """SaveOnPremConfluenceConnectorInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SaveOnPremConfluenceConnectorInfoResponse:
        """Test SaveOnPremConfluenceConnectorInfoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SaveOnPremConfluenceConnectorInfoResponse`
        """
        model = SaveOnPremConfluenceConnectorInfoResponse()
        if include_optional:
            return SaveOnPremConfluenceConnectorInfoResponse(
                message = ''
            )
        else:
            return SaveOnPremConfluenceConnectorInfoResponse(
                message = '',
        )
        """

    def testSaveOnPremConfluenceConnectorInfoResponse(self):
        """Test SaveOnPremConfluenceConnectorInfoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
