# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.role_permissions import RolePermissions

class TestRolePermissions(unittest.TestCase):
    """RolePermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RolePermissions:
        """Test RolePermissions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RolePermissions`
        """
        model = RolePermissions()
        if include_optional:
            return RolePermissions(
                create_projects = True,
                manage_team_members = True,
                access_analytics = True,
                manage_billing = True,
                manage_team_settings = True
            )
        else:
            return RolePermissions(
        )
        """

    def testRolePermissions(self):
        """Test RolePermissions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
