# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.jira_login_request import JiraLoginRequest

class TestJiraLoginRequest(unittest.TestCase):
    """JiraLoginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JiraLoginRequest:
        """Test JiraLoginRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JiraLoginRequest`
        """
        model = JiraLoginRequest()
        if include_optional:
            return JiraLoginRequest(
                redirect_uri_from_callback = ''
            )
        else:
            return JiraLoginRequest(
                redirect_uri_from_callback = '',
        )
        """

    def testJiraLoginRequest(self):
        """Test JiraLoginRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
