# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.jira_integration import JiraIntegration

class TestJiraIntegration(unittest.TestCase):
    """JiraIntegration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JiraIntegration:
        """Test JiraIntegration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JiraIntegration`
        """
        model = JiraIntegration()
        if include_optional:
            return JiraIntegration(
                uid = '',
                jira_email = ''
            )
        else:
            return JiraIntegration(
                uid = '',
                jira_email = '',
        )
        """

    def testJiraIntegration(self):
        """Test JiraIntegration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
