# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.api.team_permissions_api import TeamPermissionsApi


class TestTeamPermissionsApi(unittest.TestCase):
    """TeamPermissionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamPermissionsApi()

    def tearDown(self) -> None:
        pass

    def test_check_user_permission_teams_team_id_users_user_id_permissions_permission_get(self) -> None:
        """Test case for check_user_permission_teams_team_id_users_user_id_permissions_permission_get

        Check User Permission
        """
        pass

    def test_get_team_role_permissions_teams_team_id_role_permissions_get(self) -> None:
        """Test case for get_team_role_permissions_teams_team_id_role_permissions_get

        Get Team Role Permissions
        """
        pass

    def test_get_user_permissions_teams_team_id_users_user_id_permissions_get(self) -> None:
        """Test case for get_user_permissions_teams_team_id_users_user_id_permissions_get

        Get User Permissions
        """
        pass

    def test_initialize_team_permissions_teams_team_id_initialize_permissions_post(self) -> None:
        """Test case for initialize_team_permissions_teams_team_id_initialize_permissions_post

        Initialize Team Permissions
        """
        pass

    def test_update_team_role_permissions_teams_team_id_role_permissions_put(self) -> None:
        """Test case for update_team_role_permissions_teams_team_id_role_permissions_put

        Update Team Role Permissions
        """
        pass


if __name__ == '__main__':
    unittest.main()
