# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RolePermissions(BaseModel):
    """
    RolePermissions
    """ # noqa: E501
    create_projects: Optional[StrictBool] = False
    manage_team_members: Optional[StrictBool] = False
    access_analytics: Optional[StrictBool] = False
    manage_billing: Optional[StrictBool] = False
    manage_team_settings: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["create_projects", "manage_team_members", "access_analytics", "manage_billing", "manage_team_settings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RolePermissions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RolePermissions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "create_projects": obj.get("create_projects") if obj.get("create_projects") is not None else False,
            "manage_team_members": obj.get("manage_team_members") if obj.get("manage_team_members") is not None else False,
            "access_analytics": obj.get("access_analytics") if obj.get("access_analytics") is not None else False,
            "manage_billing": obj.get("manage_billing") if obj.get("manage_billing") is not None else False,
            "manage_team_settings": obj.get("manage_team_settings") if obj.get("manage_team_settings") is not None else False
        })
        return _obj


